import { defineRecommendation } from "./definition";

export const automationTools = [
  defineRecommendation({
    slug: "hermes-agent",
    name: "Hermes Agent",
    url: "https://hermes-agent.nousresearch.com",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-skill", "tag-open-source", "tag-cli"],
    shortDescription: "靠技能和工具调用干活、还能持续攒经验的开源 Agent。",
    recommendationReason:
      "适合想动手试 Agent 技能、工具调用和“自主执行能做到哪一步”的人——重点是摸清边界，不是找一个能撒手不管的替身。",
    usageDescription:
      "从低风险、能回滚的任务起步，给工具权限和输出验收划清楚线；别一上来就授权不可逆的外部操作。",
    suitableFor: ["想试验 Agent 技能和工具调用的人", "能给自动化任务设权限和验收的开发者"],
    unsuitableFor: ["指望零配置就完全自动跑的人", "不能接受自己维护环境、模型和工具的人"],
    strengths: ["围绕技能和工具调用组织可复用任务", "可在本地环境里探索 Agent 工作流"],
    limitations: ["自主执行不等于可靠完成", "安全边界、模型选择和运行成本得自己管"],
    pricing: "open-source",
    platforms: ["cli", "python", "macos", "windows", "linux"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "daily-use",
    featured: true,
    featuredOrder: 5,
    relatedScenarioIds: ["scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-ccswitch", "rec-bloome", "rec-happycapy"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "agent-reach",
    name: "Agent-Reach",
    url: "https://github.com/Panniantong/Agent-Reach",
    categoryId: "category-agent-automation",
    tagIds: ["tag-creative-research", "tag-agent", "tag-skill", "tag-open-source", "tag-cli"],
    shortDescription: "给 AI Agent 统一接上网页、代码仓库、视频和社区信息的检索路由层。",
    recommendationReason:
      "适合不想每个信息来源都自己写一套读取逻辑的人——把不同来源的入口统一，Agent 按任务挑合适的渠道去查。",
    usageDescription:
      "先查可用渠道和登录状态，再按来源类型读取；引用公开内容时留好原始链接，把事实和推断分开。",
    suitableFor: ["要让 Agent 查多类公开信息的人", "愿意按平台规则配置和使用检索的人"],
    unsuitableFor: ["想绕过网站权限、登录或使用限制的人", "需要保证所有来源都实时可用的人"],
    strengths: ["多类信息来源的用法集中到一个路由层", "对公开网页、GitHub、RSS 这些入口上手快"],
    limitations: ["各渠道的可用性和权限条件不一样", "检索结果还得自己判断来源可信度和时效"],
    pricing: "open-source",
    platforms: ["cli", "python"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "used-in-project",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-aihot", "rec-happycapy", "rec-colaos"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "colaos",
    name: "ColaOS",
    url: "https://colaos.ai",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-skill", "tag-desktop", "tag-local"],
    shortDescription: "把记忆、技能和电脑操作放进一个桌面 Agent 的尝试。",
    recommendationReason:
      "它想解决的不是“再开一个聊天窗口”，而是让同一个 Agent 记住上下文、接住任务并在电脑上继续干活。现在还在摸它的节奏：记忆到底帮忙，还是会把人带进误判。",
    usageDescription:
      "先让它接低风险的资料整理、计划和文件操作；涉及账号、付款、发布等动作，仍放在人工确认之后。",
    suitableFor: ["想试桌面 Agent 能否接住连续任务的人", "重视本地文件和上下文边界的人"],
    unsuitableFor: ["需要稳定替代人工执行关键操作的人", "不愿复核 Agent 记忆和操作结果的人"],
    strengths: ["把记忆、技能和电脑操作收在同一个入口", "适合从连续的小任务开始观察"],
    limitations: ["实际可靠性仍需按任务逐项验证", "涉及外部系统时必须保留人工确认"],
    pricing: "freemium",
    platforms: ["macos", "windows"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "testing",
    featured: false,
    relatedScenarioIds: ["scenario-automation"],
    relatedRecommendationIds: ["rec-agent-reach"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "bloome",
    name: "Bloome",
    url: "https://bloome.im",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-workflow", "tag-web", "tag-desktop"],
    shortDescription: "把人、聊天和多个 Agent 放进同一个对话里的协作空间。",
    recommendationReason:
      "它把 Agent 放在聊天成员的位置：同一条线程里分工、追问和回看。适合试试团队协作是不是能少一点转述和复制粘贴，不急着把它当正式协作底座。",
    usageDescription:
      "先拿一个边界清楚的小主题开房间，让每个 Agent 只负责一段工作；结论和外部动作仍由人统一确认。",
    suitableFor: ["想在聊天里试多人和多 Agent 协作的人", "需要保留讨论上下文和分工记录的人"],
    unsuitableFor: ["已经有固定协作系统且不想迁移讨论的人", "需要完全可预测的自动化执行的人"],
    strengths: ["人和 Agent 可以在同一线程里协作", "适合把分工、追问和回看留在一起"],
    limitations: ["协作方式是否适合团队仍要通过真实任务验证", "Agent 的输出和权限不能跳过人工判断"],
    pricing: "freemium",
    platforms: ["web", "macos", "windows", "ios", "android"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "testing",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent"],
    relatedRecommendationIds: ["rec-hermes-agent"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "happycapy",
    name: "Happycapy",
    url: "https://happycapy.ai",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-skill", "tag-browser-control", "tag-web"],
    shortDescription: "在浏览器里给 Agent 一台可长期使用的云端桌面。",
    recommendationReason:
      "更想看的是它把“开个环境、装技能、跑任务”收成一个浏览器入口后，能不能真的省掉准备时间。用起来像把一个可交代任务的工作台放在网页里。",
    usageDescription:
      "从不含敏感资料的网页任务开始，先确认浏览器环境、技能和结果交付是否顺手；账号和支付类操作不交给它静默执行。",
    suitableFor: ["想试浏览器内 Agent 工作台的人", "需要为任务准备隔离环境的人"],
    unsuitableFor: ["必须在本地设备或内网完成任务的人", "不接受云端环境和额度限制的人"],
    strengths: ["把浏览器环境和 Agent 技能放进同一个入口", "适合把任务交出去后再回来看结果"],
    limitations: ["云端环境的权限和资料边界需要额外确认", "复杂任务的稳定性仍需实际验证"],
    pricing: "freemium",
    platforms: ["web"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "testing",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-hermes-agent", "rec-agent-reach"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "newmax",
    name: "NewMax",
    url: "https://newmax.ai",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-desktop", "tag-local", "tag-skill"],
    shortDescription: "把本地文件、桌面应用和多模型放进同一个本地 Agent 工作台。",
    recommendationReason:
      "它把隐私和本地执行放在前面：不想把工作文件丢上云时，这条路值得试。但它能否真正融入日常，还要看任务成功率和可控性。",
    usageDescription:
      "先用副本和非关键任务测试文件操作、应用调用与定时任务；确认操作记录和恢复方式后，再逐步扩大范围。",
    suitableFor: ["想试本地优先桌面 Agent 的人", "需要在本机文件和应用之间串起任务的人"],
    unsuitableFor: ["只想在浏览器里轻量使用 Agent 的人", "不愿给桌面 Agent 明确权限范围的人"],
    strengths: ["本地文件、应用和模型可放进同一工作台", "适合从可回滚的桌面任务开始试用"],
    limitations: ["需要逐项确认模型、权限和任务的实际表现", "桌面自动化的错误影响范围更大"],
    pricing: "paid",
    platforms: ["macos", "windows"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "testing",
    featured: false,
    relatedScenarioIds: ["scenario-automation"],
    relatedRecommendationIds: [],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "kimi-work",
    name: "Kimi Work",
    url: "https://www.kimi.com/products/kimi-work",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-desktop", "tag-local", "tag-skill"],
    lastCheckedAt: "2026-07-22T00:00:00.000Z",
    shortDescription: "Kimi 的桌面端工作区，把本地文件、网页和定时任务放进同一个 Agent 入口。",
    recommendationReason:
      "Kimi K3 已进入 Kimi Work，最近正在体验它能不能把模型的理解和执行带进日常桌面任务。外界评价很高，但先不把传闻当结论：重点看它处理真实文件、网页和连续任务时是否稳定、好控。",
    usageDescription:
      "从可回滚的资料整理、网页检索和计划任务开始，先确认本地文件权限、执行记录和结果交付是否顺手；涉及账号、付款或正式发布时保留人工确认。",
    suitableFor: ["想试 Kimi K3 在桌面任务中实际表现的人", "需要在本地文件、网页和定时任务之间切换的人"],
    unsuitableFor: ["希望不审核就交给 Agent 执行关键操作的人", "只需要轻量网页聊天、不想安装桌面端的人"],
    strengths: ["把 Kimi 的模型能力放进本地桌面工作流", "支持从资料、网页到定时任务的连续尝试"],
    limitations: ["目前仍在体验阶段，任务成功率和边界需要逐项验证", "文件与网页操作的权限范围必须先设清楚"],
    pricing: "freemium",
    platforms: ["macos", "windows"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "testing",
    featured: false,
    relatedScenarioIds: [],
    relatedRecommendationIds: ["rec-colaos", "rec-newmax"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
];
