import { defineRecommendation } from "./definition";

export const automationTools = [
  defineRecommendation({
    slug: "hermes-agent",
    name: "Hermes Agent",
    url: "https://hermes-agent.nousresearch.com",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-skill", "tag-open-source", "tag-cli"],
    shortDescription: "靠技能和工具调用干活、还能持续攒经验的开源 Agent。",
    recommendationReason:
      "适合想动手试 Agent 技能、工具调用和“自主执行能做到哪一步”的人——重点是摸清边界，不是找个能撒手不管的替身。",
    usageDescription:
      "从低风险、能回滚的任务起步，给工具权限和输出验收划清楚线；别一上来就授权不可逆的外部操作。",
    suitableFor: ["想试验 Agent 技能和工具调用的人", "能给自动化任务设权限和验收的开发者"],
    unsuitableFor: ["指望零配置就完全自动跑的人", "不能接受自己维护环境、模型和工具的人"],
    strengths: ["围绕技能和工具调用组织可复用任务", "可在本地环境里探索 Agent 工作流"],
    limitations: ["自主执行不等于可靠完成", "安全边界、模型选择和运行成本得自己管"],
    pricing: "open-source",
    platforms: ["cli", "python", "macos", "windows", "linux"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-dify", "rec-n8n", "rec-ccswitch"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "dify",
    name: "Dify",
    url: "https://dify.ai",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-workflow", "tag-api", "tag-self-hostable"],
    shortDescription: "不用从零写界面、快速搭出带模型和工作流的 AI 应用的平台。",
    recommendationReason:
      "想验证一个带模型、知识库或工作流的 AI 应用，它能把“做个能跑的 demo”这件事的时间压到最短。适合先跑通、再决定要不要深入。",
    usageDescription:
      "先用小范围流程验证输入、提示词和输出质量，再决定接不接更多数据源、权限和发布渠道。",
    suitableFor: ["想可视化搭 AI 应用或流程的人", "想在托管和自托管之间留选择的人"],
    unsuitableFor: ["底层编排逻辑要完全自定义的复杂系统", "没时间维护模型密钥、数据和运行环境的人"],
    strengths: ["让 AI 应用和工作流的验证更快", "提供自托管选项"],
    limitations: ["流程一复杂还是要工程化治理", "模型、知识库和权限都得单独查"],
    pricing: "freemium",
    platforms: ["web", "self-hosted"],
    isOpenSource: false,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-n8n", "rec-hermes-agent", "rec-agent-reach"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "n8n",
    name: "n8n",
    url: "https://n8n.io",
    categoryId: "category-agent-automation",
    tagIds: ["tag-workflow", "tag-workflow-building", "tag-api", "tag-self-hostable"],
    shortDescription: "用节点把跨服务的重复操作画成可看、可改的流程。",
    recommendationReason:
      "那种“A 发生就去做 B”的规则类操作，画成节点一目了然，谁都能看懂、都能改。适合把固定流程沉淀下来、不再每次手动跑的人。",
    usageDescription:
      "从一条输入输出都清楚、失败了知道怎么办的流程起步；只要涉及写操作、付款、删数据这类不可逆动作，就给它挂一个人工确认节点，别让它静默执行。",
    suitableFor: ["要连多个服务、减少重复手动操作的人", "愿意持续维护流程和异常处理的人"],
    unsuitableFor: ["业务规则和失败后果都说不清的任务", "完全不想碰配置的人"],
    strengths: ["跨服务步骤可视化地串起来", "支持自托管部署"],
    limitations: [
      "不是传统意义的开源免费，商用范围按官方当前许可看，别想当然",
      "自动化一旦失败、权限或数据出问题，得自己兜底",
    ],
    pricing: "freemium",
    platforms: ["web", "self-hosted"],
    isOpenSource: false,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-dify", "rec-hermes-agent", "rec-agent-reach"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "agent-reach",
    name: "Agent-Reach",
    url: "https://github.com/Panniantong/Agent-Reach",
    categoryId: "category-agent-automation",
    tagIds: ["tag-creative-research", "tag-agent", "tag-skill", "tag-open-source", "tag-cli"],
    shortDescription: "给 AI Agent 统一接上网页、代码仓库、视频和社区信息的检索路由层。",
    recommendationReason:
      "适合不想每个信息来源都自己写一套读取逻辑的人——把不同来源的入口统一，Agent 按任务挑合适的渠道去查。",
    usageDescription:
      "先查可用渠道和登录状态，再按来源类型读取；引用公开内容时留好原始链接，把事实和推断分开。",
    suitableFor: ["要让 Agent 查多类公开信息的人", "愿意按平台规则配置和使用检索的人"],
    unsuitableFor: ["想绕过网站权限、登录或使用限制的人", "需要保证所有来源都实时可用的人"],
    strengths: ["多类信息来源的用法集中到一个路由层", "对公开网页、GitHub、RSS 这些入口上手快"],
    limitations: ["各渠道的可用性和权限条件不一样", "检索结果还得自己判断来源可信度和时效"],
    pricing: "open-source",
    platforms: ["cli", "python"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-aihot", "rec-dify", "rec-n8n"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
];
