import { defineRecommendation } from "./definition";

export const creationTools = [
  defineRecommendation({
    slug: "open-design",
    name: "OpenDesign",
    url: "https://open-design.ai",
    categoryId: "category-content-creation",
    tagIds: ["tag-ui-design", "tag-design-system", "tag-skill", "tag-open-source", "tag-cli"],
    shortDescription:
      "让本地编码 Agent 按 DESIGN.md 和可组合设计技能产出界面方案的开源工作空间。",
    recommendationReason:
      "适合把“视觉方向 + 设计约束”直接喂给编码 Agent 去执行——不用在设计稿和代码之间来回翻译，设计规则能当项目资产复用。",
    usageDescription:
      "先定页面目标、内容层级和视觉参考，再让 Agent 生成或迭代；最后按真实设备和业务内容检查可用性。",
    suitableFor: ["用 AI 编码 Agent 做界面、想保持设计一致的人", "要把设计规范沉淀成可复用规则的人"],
    unsuitableFor: ["只想要传统多人协作设计文件的人", "不愿维护设计约束、不审生成界面的人"],
    strengths: ["把设计规则和编码 Agent 的执行接起来", "设计技能和规则能当资产复用"],
    limitations: ["生成界面仍要过真实内容、响应式和无障碍检查", "依赖所选的 Agent、模型和本地环境"],
    pricing: "open-source",
    platforms: ["cli", "web"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: [
      "scenario-ai-website",
      "scenario-media-production",
      "scenario-indie-inspiration",
    ],
    relatedRecommendationIds: ["rec-awesome-design-md", "rec-cursor", "rec-codex"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "kling",
    name: "Kling",
    url: "https://klingai.com",
    categoryId: "category-content-creation",
    tagIds: ["tag-video-generation", "tag-content-creation", "tag-web"],
    shortDescription: "用文字或图片生成、延展和编辑视频素材的在线工具。",
    recommendationReason:
      "适合正式制作前先把动态画面、镜头氛围和概念试出来——比干想要快，能早点看出方向行不行。",
    usageDescription:
      "先用短片段验证画面、运动和风格，再决定要不要进剪辑和正式交付；保留源文件，确认好商用和素材权利。",
    suitableFor: ["要快速验证视频创意和概念镜头的人", "愿意多轮调 prompt 和素材的人"],
    unsuitableFor: ["要求每次输出都完全可控、可复现的人", "不能接受生成等待、额度或版权核查的人"],
    strengths: ["能较快把静态灵感转成动态素材", "适合前期概念验证和试作"],
    limitations: ["细节、人物一致性和运动得逐次查", "套餐、额度和商用权利以当前规则为准"],
    pricing: "freemium",
    platforms: ["web"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-media-production"],
    relatedRecommendationIds: ["rec-midjourney", "rec-remotion", "rec-youmind"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "midjourney",
    name: "Midjourney",
    url: "https://www.midjourney.com",
    categoryId: "category-content-creation",
    tagIds: ["tag-image-generation", "tag-content-creation", "tag-web", "tag-paid"],
    shortDescription: "动手做之前，先拿它快速试画面风格、构图和氛围方向。",
    recommendationReason:
      "风格、构图、情绪这些事，干想要半天；丢进去几轮就能看出方向对不对。适合在设计或制作真正开始前，先把视觉调性定下来。",
    usageDescription:
      "把主题、画面重点和参考方向写清楚，靠多轮生成去筛；拿去正式发布前，自己检查素材来源、图里文字细节和使用权。",
    suitableFor: ["需要快速探索视觉方向的人", "愿意反复筛、反复调 prompt 的人"],
    unsuitableFor: ["要求图里每个细节、文字和品牌元素都完全可控的人", "需要本地离线生成或自托管的人"],
    strengths: ["短时间内能铺出多种视觉方向", "可作为设计和视频前期的灵感来源"],
    limitations: ["细节、文字和一致性基本要你再修", "输出和使用权规则发布前必须确认"],
    pricing: "paid",
    platforms: ["web"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-media-production"],
    relatedRecommendationIds: ["rec-kling", "rec-catchmeta", "rec-open-design"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "remotion",
    name: "Remotion",
    url: "https://www.remotion.dev",
    categoryId: "category-content-creation",
    tagIds: ["tag-programmatic-media", "tag-video-generation", "tag-code-generation", "tag-react"],
    shortDescription: "用 React 写视频——字幕、数据、动画都在代码里，改一处整批跟着变。",
    recommendationReason:
      "会写代码的人做视频，这条路最顺。模板和数据驱动意味着改一个变量、整批视频跟着更新——这种可复用、可批量的感觉，传统剪辑软件给不了。",
    usageDescription:
      "先建几个稳定的画面模板和数据输入，再慢慢加动画；输出前在目标尺寸、字体和渲染环境里把成片过一遍。",
    suitableFor: ["想把视频内容模板化、自动化的人", "会或愿意用 React 的创作者和开发者"],
    unsuitableFor: ["只想零代码、拖一下出片的人", "没时间维护素材、字体和渲染环境的人"],
    strengths: ["视频结构能随代码和数据复用", "适合批量生成格式一致的内容"],
    limitations: ["要开发和渲染环境", "动画质量还是取决于设计、素材和人工预览"],
    pricing: "freemium",
    platforms: ["nodejs", "react"],
    isOpenSource: false,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-media-production"],
    relatedRecommendationIds: ["rec-kling", "rec-ppt-master", "rec-guizang-ppt-skill"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "ppt-master",
    name: "PPT Master",
    url: "https://github.com/hugohe3/ppt-master",
    categoryId: "category-content-creation",
    tagIds: ["tag-presentation", "tag-skill", "tag-open-source", "tag-local"],
    shortDescription: "在本地 AI 编码环境里、从资料直接生成可继续编辑的 PPTX 的工作流。",
    recommendationReason:
      "适合想要 PPTX 原生可编辑能力、又想借 AI 把内容整理和排版初稿提速的人——交付的是真能改的 PowerPoint，不是一张图。",
    usageDescription:
      "先理好输入资料和目标受众，再让它出初稿；重点看叙事、数据、字体和放映效果，别只盯着“生成成功了没”。",
    suitableFor: ["要交付可编辑 PPTX 的人", "愿意在本地 AI 编码环境里跑生成流程的人"],
    unsuitableFor: ["只需要在线演示链接的人", "不愿装本地环境、不人工检查版式的人"],
    strengths: ["输出以可继续编辑的 PowerPoint 为目标", "适合把资料转成能迭代的演示初稿"],
    limitations: ["生成质量受输入材料、模型和模板影响", "图表、排版和事实内容必须逐页复核"],
    pricing: "open-source",
    platforms: ["python", "cli", "macos", "windows", "linux"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-media-production"],
    relatedRecommendationIds: ["rec-guizang-ppt-skill", "rec-remotion", "rec-chatgpt"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "guizang-ppt-skill",
    name: "guizang-ppt-skill",
    url: "https://github.com/op7418/guizang-ppt-skill",
    categoryId: "category-content-creation",
    tagIds: ["tag-presentation", "tag-skill", "tag-open-source", "tag-web"],
    shortDescription: "给 Codex、Claude Code 等 Agent 生成单文件网页演示、配图和封面的技能。",
    recommendationReason:
      "适合要快速做出能在浏览器里展示的演示内容、又想保住一套明确视觉方向的人——产出的是便于在线分享的单文件，不是传统 PPT。",
    usageDescription:
      "先确认受众、故事线和展示场景，再挑合适的视觉系统；在目标设备上检查翻页、图片、文字密度和性能。",
    suitableFor: ["要快速做网页演示或内容封面的人", "在 Agent 环境里做内容和视觉协作的人"],
    unsuitableFor: ["必须交付原生 PPTX 文件的人", "不愿检查网页兼容性和展示效果的人"],
    strengths: ["把演示、配图和封面放进统一创作流程", "适合产出便于在线分享的单文件演示"],
    limitations: ["网页演示不等于可编辑 PowerPoint", "图片版权、文字准确性和设备兼容性仍要复核"],
    pricing: "open-source",
    platforms: ["cli", "web"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-media-production"],
    relatedRecommendationIds: ["rec-ppt-master", "rec-remotion", "rec-open-design"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
];
