import { defineRecommendation } from "./definition";

export const developmentTools = [
  defineRecommendation({
    slug: "claude-code",
    name: "Claude Code",
    url: "https://claude.com/product/claude-code",
    categoryId: "category-ai-coding",
    tagIds: ["tag-agent", "tag-code-generation", "tag-cli", "tag-paid"],
    shortDescription: "在终端里理解整个项目、帮你把开发任务从头做到尾的编码 Agent。",
    recommendationReason:
      "它的长处在“连续”——读完代码、动手改、跑测试、再把改动讲清楚，这套流程不用你切来切去。适合需要围绕项目上下文持续推进的开发工作。",
    usageDescription:
      "先说清目标、文件范围和不能动的部分，让它先给计划、再动手；提交前自己看一遍 diff、跑一遍项目的检查，别整段照单全收。",
    suitableFor: ["习惯在终端工作、重视项目上下文的开发者", "需要处理跨多文件改动、又愿意审核的人"],
    unsuitableFor: ["只想按个按钮出代码、不愿读改动的人", "没有可运行验证环境、无法兜底的任务"],
    strengths: ["把探索和实施串成一条连续流程", "改动痕迹清晰，方便回头审"],
    limitations: ["对任务描述和上下文质量很敏感", "不能替代安全审查、架构判断和发布责任"],
    pricing: "paid",
    platforms: ["cli", "macos", "windows", "linux"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: [
      "scenario-ai-website",
      "scenario-build-agent",
      "scenario-indie-inspiration",
    ],
    relatedRecommendationIds: ["rec-codex", "rec-cursor", "rec-ccswitch"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "cursor",
    name: "Cursor",
    url: "https://cursor.com",
    categoryId: "category-ai-coding",
    tagIds: ["tag-code-generation", "tag-agent", "tag-desktop", "tag-paid"],
    shortDescription: "把代码编辑、项目上下文和 AI 协作放在一个编辑器里的开发工具。",
    recommendationReason:
      "适合“读代码、局部改、马上验证”这种来回切的日常活——不用在编辑器和 AI 对话框之间反复横跳，路径短。",
    usageDescription:
      "先在编辑器里确认要改的位置和影响范围，再让 AI 动手做局部修改；跨模块的改动留个清单，别一口气全交出去。",
    suitableFor: ["想直接在编辑器里用 AI 协作的开发者", "以局部迭代、快速反馈为主的项目"],
    unsuitableFor: ["不愿读改动、不跑测试的人", "必须完全离线开发的人"],
    strengths: ["读代码、编辑、对话的操作路径很短", "适合从小改动开始一点点推"],
    limitations: ["复杂任务还是要自己拆分和审", "不同模型、套餐和网络状态会影响体验"],
    pricing: "freemium",
    platforms: ["macos", "windows", "linux"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-ai-website", "scenario-indie-inspiration"],
    relatedRecommendationIds: ["rec-codex", "rec-claude-code"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "ccswitch",
    name: "CCSwitch",
    url: "https://ccswitch.io",
    categoryId: "category-ai-coding",
    tagIds: ["tag-provider-management", "tag-agent", "tag-cli", "tag-desktop", "tag-open-source"],
    shortDescription: "把多个 AI 编码工具的配置和服务集中收拢的桌面工具。",
    recommendationReason:
      "同时用 Claude Code、Codex 好几套工具的人都知道，配置和环境变量切来切去有多烦——这工具就是来治这个的，少在配置里浪费时间。",
    usageDescription:
      "把常用的服务和工作环境整理进来；切之前确认当前项目要用的模型、权限和费用设置。",
    suitableFor: ["同时用多个 AI 编码工具的人", "想把模型、服务和工具配置统一管起来的人"],
    unsuitableFor: ["只用单一工具、没有切换需求的人", "不愿把配置集中放到第三方桌面工具里的人"],
    strengths: ["减少多工具之间的配置切换", "覆盖好几个常见的编码 Agent 入口"],
    limitations: ["服务凭据和路由还是得自己核对", "各工具的兼容范围会随版本变"],
    pricing: "open-source",
    platforms: ["macos", "windows", "linux"],
    isOpenSource: true,
    selfHostable: false,
    relationship: "daily-use",
    featured: true,
    featuredOrder: 3,
    relatedScenarioIds: ["scenario-ai-website", "scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-codex", "rec-claude-code", "rec-hermes-agent"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "vercel",
    name: "Vercel",
    url: "https://vercel.com",
    categoryId: "category-ai-coding",
    tagIds: ["tag-deployment", "tag-web", "tag-api"],
    shortDescription: "把代码提交快速变成可访问预览、审核后发布上线的平台。",
    recommendationReason:
      "改完东西想马上看到效果、想丢个链接给别人看，它最顺手。适合前端项目持续迭代、频繁出预览的工作方式。",
    usageDescription:
      "预览环境用来看页面和交互，正式环境只放通过验证的提交；上线前查一遍环境变量、域名和访问权限。",
    suitableFor: ["用 Git 驱动发布 Web 项目的人", "需要预览链接来协作和审核的团队或个人"],
    unsuitableFor: ["要完全自建基础设施的人", "不想依赖托管发布平台的人"],
    strengths: ["预览和正式发布的路径很清晰", "适合前端项目持续迭代"],
    limitations: ["费用、构建限制和运行环境按套餐来，得自己核对", "替代不了应用自己的监控和备份"],
    pricing: "freemium",
    platforms: ["web"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-ai-website", "scenario-indie-inspiration"],
    relatedRecommendationIds: ["rec-cloudflare", "rec-cursor"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "cloudflare",
    name: "Cloudflare",
    url: "https://www.cloudflare.com",
    categoryId: "category-ai-coding",
    tagIds: ["tag-deployment", "tag-web", "tag-api", "tag-database"],
    shortDescription: "绑一张卡就能在边缘网络上白嫖一整套部署能力（计算、静态站、存储、数据库）的平台。",
    recommendationReason:
      "它确实做到了“一张信用卡免费用很多”——Workers、Pages、R2、D1、KV 全有免费额度，个人项目几乎跑不满。R2 还免出口流量费，这点在别家云上是要收钱的。",
    usageDescription:
      "静态站丢 Pages，带逻辑的接口丢 Workers，文件丢 R2，结构化数据丢 D1；绑卡只是验证身份，免费额度内基本不扣费，超了再按用量走。",
    suitableFor: ["想零成本上线 Web 项目的人", "不想管服务器、想就近部署到全球边缘的人"],
    unsuitableFor: ["要长连接、重计算或跑传统后端服务的人", "不想绑卡的人"],
    strengths: ["免费额度覆盖面广，个人项目够用", "R2 对象存储零出口流量费", "部署到全球边缘网络，访问快"],
    limitations: [
      "要用 R2、D1 这些得先绑卡验证",
      "免费额度按日或按月算，不是无限",
      "R2 读取操作超量会收费，高流量读图也可能产生账单",
    ],
    pricing: "freemium",
    platforms: ["web"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-ai-website", "scenario-indie-inspiration"],
    relatedRecommendationIds: ["rec-vercel", "rec-cursor"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
];
