import { defineRecommendation } from "./definition";

export const knowledgeTools = [
  defineRecommendation({
    slug: "obsidian",
    name: "Obsidian",
    url: "https://obsidian.md",
    categoryId: "category-knowledge",
    tagIds: [
      "tag-notes",
      "tag-knowledge-base",
      "tag-personal-knowledge",
      "tag-local",
      "tag-desktop",
    ],
    shortDescription: "以本地 Markdown 文件和双链为核心的个人知识库。",
    recommendationReason:
      "笔记就是本地文件，你想怎么组织、怎么迁移、怎么备份都由你说了算。适合想长期积累、不被某个平台锁死的人。",
    usageDescription:
      "从几个稳定的文件夹和标签起步，慢慢加链接和模板；别一上来就堆插件和规则，为了“系统感”反而维护不动。",
    suitableFor: ["看重本地文件、长期积累和可迁移性的人", "愿意花时间养自己的笔记结构的人"],
    unsuitableFor: ["要多人实时改同一份文档的人", "想零配置、开箱就有现成团队知识库的人"],
    strengths: ["本地文件，迁移和备份边界清楚", "适合一点点长出属于自己的知识网络"],
    limitations: ["同步、协作和插件得自己规划", "结构过度设计会增加维护成本"],
    pricing: "freemium",
    platforms: ["macos", "windows", "linux", "ios", "android"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "daily-use",
    featured: true,
    featuredOrder: 4,
    relatedScenarioIds: ["scenario-knowledge-base"],
    relatedRecommendationIds: ["rec-notion", "rec-youmind"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "notion",
    name: "Notion",
    url: "https://www.notion.com",
    categoryId: "category-knowledge",
    tagIds: ["tag-notes", "tag-knowledge-base", "tag-personal-knowledge", "tag-web"],
    shortDescription: "把文档、数据库和协作放在同一个空间的在线信息整理工具。",
    recommendationReason:
      "项目资料、内容清单、协作页面堆在一处，谁都能看、都能维护。适合要把信息共享出去、而不是只存在自己本地的工作。",
    usageDescription:
      "拿它装需要共享、追踪和展示的内容；每类数据库只留几个明确字段，别把所有东西塞进一张大表。",
    suitableFor: ["要共享资料或一起维护内容的人", "想用页面和数据库组织项目的人"],
    unsuitableFor: ["必须离线保存全部资料的人", "想完全自由控制底层文件结构的人"],
    strengths: ["文档和结构化信息能放在同一处", "适合用模板统一重复内容"],
    limitations: ["数据库一复杂就难维护", "离线能力和数据导出方式得自己评估"],
    pricing: "freemium",
    platforms: ["web", "macos", "windows", "ios", "android"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-knowledge-base", "scenario-indie-inspiration"],
    relatedRecommendationIds: ["rec-obsidian", "rec-youmind"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "youmind",
    name: "YouMind",
    url: "https://youmind.com",
    categoryId: "category-knowledge",
    tagIds: ["tag-creative-research", "tag-notes", "tag-content-creation", "tag-web"],
    shortDescription: "把网页、图片和零散想法汇到一处、再从材料出发出创作稿的工作空间。",
    recommendationReason:
      "适合“先攒素材、再动笔”这种创作流程——不用开一堆标签页和文档来回翻，材料和草稿在同一个地方长出来。",
    usageDescription:
      "先给一个主题单独建块素材板，再让 AI 帮忙提炼结构和草稿；关键来源和最终措辞自己确认。",
    suitableFor: ["要从一堆素材里持续产出内容的人", "想把收集、整理和初稿放在一处的人"],
    unsuitableFor: ["只需要纯文本本地笔记的人", "对来源和准确性要求极高、却不愿复核的人"],
    strengths: ["从攒素材到出稿的衔接短", "适合按主题管灵感和资料"],
    limitations: ["生成内容不能替代来源核验", "产品能力和套餐得用到时再复查"],
    pricing: "freemium",
    platforms: ["web", "ios"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-knowledge-base", "scenario-media-production"],
    relatedRecommendationIds: ["rec-obsidian", "rec-notion", "rec-aihot"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
  defineRecommendation({
    slug: "aihot",
    name: "AIHot",
    url: "https://aihot.virxact.com",
    categoryId: "category-indie",
    tagIds: ["tag-ai-news", "tag-rss", "tag-creative-research", "tag-web", "tag-api"],
    shortDescription: "把 AI 一手信源、资讯、论文和社区动态汇到一个入口的信息站。",
    recommendationReason:
      "适合不想在十几个来源之间来回翻的人——值得追的变化集中在一处，先看它再决定要不要深挖。",
    usageDescription:
      "当成发现线索的入口，不是事实的唯一依据；遇到重要发布、价格和能力变化，回原始公告确认。",
    suitableFor: ["想持续追 AI 工具和行业信息的人", "要为研究或内容创作攒线索的人"],
    unsuitableFor: ["只接受单一官方渠道的人", "需要实时、无遗漏的专业监测服务的人"],
    strengths: ["多类 AI 信息汇到一个浏览入口", "提供适合继续读或订阅的线索"],
    limitations: ["聚合内容可能有延迟或来源质量参差", "重要结论必须追溯到原始来源"],
    pricing: "free",
    platforms: ["web", "api"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: [
      "scenario-knowledge-base",
      "scenario-indie-inspiration",
      "scenario-automation",
    ],
    relatedRecommendationIds: ["rec-youmind", "rec-agent-reach", "rec-catchmeta"],
    relatedProjectIds: [],
    relatedArticles: [],
  }),
];
