import type { Category } from "../types";

const createdAt = "2026-07-10T00:00:00.000Z";

export const categories: Category[] = [
  {
    id: "category-ai-assistant",
    slug: "ai-assistant",
    name: "AI 助手与模型",
    shortDescription: "对话模型、搜索助手、本地模型与多模型客户端。",
    longDescription: "用于理解、生成和检索信息的通用 AI 助手，以及支持本地模型运行的基础工具。",
    iconKey: "assistant",
    order: 1,
    visible: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "category-ai-coding",
    slug: "ai-coding",
    name: "AI 编程与开发",
    shortDescription: "从需求到代码、调试、数据服务和部署的开发工具。",
    longDescription: "覆盖代码生成、编辑器、数据库服务与部署平台，服务于完整的软件交付流程。",
    iconKey: "coding",
    order: 2,
    visible: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "category-agent-automation",
    slug: "agent-automation",
    name: "Agent 与自动化",
    shortDescription: "Agent 框架、工作流平台和浏览器自动化工具。",
    longDescription: "用于设计 Agent 流程、连接外部工具、执行自动化任务和编排复杂工作流。",
    iconKey: "agent",
    order: 3,
    visible: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "category-knowledge",
    slug: "knowledge",
    name: "知识与信息管理",
    shortDescription: "信息收集、阅读、笔记、知识库与文献管理工具。",
    longDescription: "支持从信息获取到长期整理、引用和检索的个人与团队知识工作流。",
    iconKey: "knowledge",
    order: 4,
    visible: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "category-content-creation",
    slug: "content-creation",
    name: "内容与视觉创作",
    shortDescription: "图像、视频、界面设计和内容生产工具。",
    longDescription: "面向视觉构思、图像与视频生成、界面设计及内容整理的创作工具。",
    iconKey: "creation",
    order: 5,
    visible: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "category-indie",
    slug: "indie",
    name: "独立产品与灵感",
    shortDescription: "适合独立开发、内容订阅、草图和程序化创作的工具。",
    longDescription: "帮助独立创作者发现信号、整理想法、表达概念并制作可发布内容。",
    iconKey: "indie",
    order: 6,
    visible: true,
    createdAt,
    updatedAt: createdAt,
  },
];
