import type { Project } from "../types";

const createdAt = "2026-07-10T00:00:00.000Z";

export const projects: Project[] = [
  {
    id: "project-yemai-reading-assistant",
    slug: "yemai-reading-assistant",
    name: "页脉 · AI 阅读助手",
    shortDescription:
      "在 Chrome 侧边栏中结合网页、划词和文件与 AI 连续对话，并收藏值得保留的回答。",
    problem: "阅读材料与 AI 对话分散在不同位置，后续很难找到问题、来源和有价值的回答。",
    coreFeatures: ["网页与划词引用", "连续对话与分支", "回答收藏与本地工作区"],
    techStack: ["Chrome Extension", "WXT", "React", "TypeScript"],
    status: "launched",
    publishStatus: "published",
    coverImage: "/assets/icons/project-yemai.png",
    projectUrl: "https://github.com/IDCBAD/yemai-reading-assistant",
    createdAt: "2026-08-09T00:00:00.000Z",
    updatedAt: "2026-09-27T00:00:00.000Z",
  },
  {
    id: "project-personal-blog",
    slug: "personal-blog",
    name: "余一的 AI 观察备忘录",
    shortDescription: "持续记录 AI、工具和独立开发中的观察与实践。",
    problem: "把零散的实践、判断和项目记录沉淀成可长期回看的公开内容。",
    coreFeatures: ["文章发布", "主题归档", "项目记录"],
    techStack: ["Next.js", "MDX", "Vercel"],
    status: "launched",
    publishStatus: "published",
    coverImage: "/assets/icons/project-personal-blog.png",
    projectUrl: "https://blog.yuyi-ai.top/",
    createdAt,
    updatedAt: "2026-07-22T00:00:00.000Z",
  },
  {
    id: "project-recommendation-list",
    slug: "ai-recommendation-list",
    name: "余一的 AI 推荐清单",
    shortDescription: "按真实使用关系整理工具、场景与项目的 AI 推荐清单。",
    problem: "让工具选择不只停在功能罗列，也能看到使用关系、理由和限制。",
    coreFeatures: ["分类浏览", "场景工作流", "推荐关系"],
    techStack: ["Next.js", "TypeScript", "Vitest"],
    status: "launched",
    publishStatus: "published",
    coverImage: "/assets/images/site-logo.png",
    projectUrl: "https://picks.yuyi-ai.top/",
    createdAt,
    updatedAt: "2026-07-22T00:00:00.000Z",
  },
  {
    id: "project-ai-mini-tools",
    slug: "ai-mini-tools",
    name: "AI 小工具集",
    shortDescription: "面向日常创作与效率场景的一组轻量 AI 小工具，目前仍在规划。",
    problem: "把零散、一次性的需求做成一组真正能随手打开的小工具。",
    coreFeatures: ["小工具集合", "轻量工作流", "快速访问"],
    techStack: ["AI", "Web", "Product Design"],
    status: "prototype",
    publishStatus: "published",
    createdAt,
    updatedAt: "2026-07-22T00:00:00.000Z",
  },
];
