import type { Recommendation } from "../types";

type RecommendationSeed = Pick<
  Recommendation,
  | "id"
  | "slug"
  | "name"
  | "url"
  | "categoryId"
  | "tagIds"
  | "shortDescription"
  | "recommendationReason"
  | "pricing"
  | "platforms"
  | "isOpenSource"
  | "selfHostable"
  | "relationship"
  | "featured"
  | "relatedScenarioIds"
  | "relatedRecommendationIds"
  | "relatedProjectIds"
  | "createdAt"
  | "updatedAt"
> & {
  featuredOrder?: number;
};

function defineRecommendation(seed: RecommendationSeed): Recommendation {
  return {
    ...seed,
    usageDescription: "原型未提供具体个人使用方式，正式发布前需要补充并复核。",
    suitableFor: ["正在评估该类能力并希望比较实际适用范围的人。"],
    unsuitableFor: ["要求未经复核的个人结论或固定定价承诺的人。"],
    strengths: [seed.shortDescription],
    limitations: ["定价、可用地区和个人评价需要在正式发布前再次检查。"],
    availabilityStatus: "available",
    publishStatus: "published",
    editorialStatus: "needs-review",
    relatedArticles: [],
    publishedAt: seed.createdAt,
    lastCheckedAt: "2026-07-10T00:00:00.000Z",
    updateLogs: [],
  };
}

export const recommendations: Recommendation[] = [
  defineRecommendation({
    id: "rec-chatgpt",
    slug: "chatgpt",
    name: "ChatGPT",
    url: "https://chat.openai.com",
    categoryId: "category-ai-assistant",
    tagIds: ["tag-conversation", "tag-code-generation", "tag-web", "tag-paid"],
    shortDescription: "通用 AI 对话助手，覆盖写作、编程和分析。",
    recommendationReason: "原型资料将其作为通用对话与分析工具收录，个人判断仍需编辑复核。",
    pricing: "freemium",
    platforms: ["web", "ios", "android"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: [
      "scenario-ai-website",
      "scenario-build-agent",
      "scenario-knowledge-base",
      "scenario-media-production",
    ],
    relatedRecommendationIds: ["rec-claude"],
    relatedProjectIds: [],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-07-01T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-claude",
    slug: "claude",
    name: "Claude",
    url: "https://claude.ai",
    categoryId: "category-ai-assistant",
    tagIds: ["tag-conversation", "tag-code-generation", "tag-web", "tag-paid"],
    shortDescription: "支持长文本理解与代码生成的 AI 助手。",
    recommendationReason: "原型资料突出其长文本和代码能力，具体个人评价仍需编辑复核。",
    pricing: "freemium",
    platforms: ["web", "ios", "android"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "daily-use",
    featured: true,
    featuredOrder: 1,
    relatedScenarioIds: [
      "scenario-ai-website",
      "scenario-build-agent",
      "scenario-knowledge-base",
      "scenario-media-production",
    ],
    relatedRecommendationIds: ["rec-chatgpt", "rec-claude-code"],
    relatedProjectIds: [],
    createdAt: "2026-01-02T00:00:00.000Z",
    updatedAt: "2026-07-10T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-ollama",
    slug: "ollama",
    name: "Ollama",
    url: "https://ollama.com",
    categoryId: "category-ai-assistant",
    tagIds: ["tag-local-model", "tag-open-source", "tag-local", "tag-desktop"],
    shortDescription: "用于在本地设备运行大语言模型的命令行工具。",
    recommendationReason: "原型资料将其作为本地模型运行工具收录，使用判断仍需编辑复核。",
    pricing: "open-source",
    platforms: ["macos", "windows", "linux", "cli"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent", "scenario-knowledge-base"],
    relatedRecommendationIds: [],
    relatedProjectIds: [],
    createdAt: "2026-01-03T00:00:00.000Z",
    updatedAt: "2026-06-28T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-claude-code",
    slug: "claude-code",
    name: "Claude Code",
    url: "https://claude.ai/code",
    categoryId: "category-ai-coding",
    tagIds: ["tag-agent", "tag-code-generation", "tag-paid"],
    shortDescription: "在终端中理解项目上下文并执行多文件修改的编程 Agent。",
    recommendationReason: "原型资料将其列为终端编程 Agent，个人工作流描述仍需编辑复核。",
    pricing: "paid",
    platforms: ["cli"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "daily-use",
    featured: false,
    relatedScenarioIds: ["scenario-ai-website", "scenario-indie-inspiration"],
    relatedRecommendationIds: ["rec-cursor", "rec-claude"],
    relatedProjectIds: ["project-recommendation-list"],
    createdAt: "2026-01-04T00:00:00.000Z",
    updatedAt: "2026-07-09T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-cursor",
    slug: "cursor",
    name: "Cursor",
    url: "https://cursor.com",
    categoryId: "category-ai-coding",
    tagIds: ["tag-code-generation", "tag-desktop", "tag-paid", "tag-indie-development"],
    shortDescription: "基于代码库上下文进行编辑和生成的 AI 代码编辑器。",
    recommendationReason: "原型资料将其列为项目使用过的 AI 编辑器，具体经验仍需编辑复核。",
    pricing: "freemium",
    platforms: ["macos", "windows", "linux"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "used-in-project",
    featured: false,
    relatedScenarioIds: ["scenario-ai-website", "scenario-indie-inspiration"],
    relatedRecommendationIds: ["rec-claude-code"],
    relatedProjectIds: ["project-recommendation-list"],
    createdAt: "2026-01-05T00:00:00.000Z",
    updatedAt: "2026-07-08T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-supabase",
    slug: "supabase",
    name: "Supabase",
    url: "https://supabase.com",
    categoryId: "category-ai-coding",
    tagIds: ["tag-database", "tag-open-source", "tag-self-hostable", "tag-web"],
    shortDescription: "以 Postgres 为核心并提供认证和实时能力的后端平台。",
    recommendationReason: "原型资料将其作为开源后端平台收录，项目使用说明仍需编辑复核。",
    pricing: "freemium",
    platforms: ["web", "self-hosted"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-ai-website"],
    relatedRecommendationIds: ["rec-vercel"],
    relatedProjectIds: ["project-recommendation-list"],
    createdAt: "2026-01-06T00:00:00.000Z",
    updatedAt: "2026-07-07T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-vercel",
    slug: "vercel",
    name: "Vercel",
    url: "https://vercel.com",
    categoryId: "category-ai-coding",
    tagIds: ["tag-deployment", "tag-web", "tag-indie-development"],
    shortDescription: "面向 Web 应用的部署和持续交付平台。",
    recommendationReason: "原型资料将其作为日常使用的部署平台收录，个人判断仍需编辑复核。",
    pricing: "freemium",
    platforms: ["web"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "daily-use",
    featured: true,
    featuredOrder: 2,
    relatedScenarioIds: ["scenario-ai-website", "scenario-indie-inspiration"],
    relatedRecommendationIds: ["rec-supabase"],
    relatedProjectIds: ["project-personal-blog", "project-recommendation-list"],
    createdAt: "2026-01-07T00:00:00.000Z",
    updatedAt: "2026-07-06T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-langgraph",
    slug: "langgraph",
    name: "LangGraph",
    url: "https://langchain.com/langgraph",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-workflow", "tag-open-source", "tag-agent-development"],
    shortDescription: "基于图结构组织状态、分支和循环的 Agent 编排框架。",
    recommendationReason: "原型资料将其列为项目使用过的 Agent 框架，实践结论仍需编辑复核。",
    pricing: "open-source",
    platforms: ["python"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "used-in-project",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent"],
    relatedRecommendationIds: ["rec-dify"],
    relatedProjectIds: ["project-agent-analysis"],
    createdAt: "2026-01-08T00:00:00.000Z",
    updatedAt: "2026-07-05T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-dify",
    slug: "dify",
    name: "Dify",
    url: "https://dify.ai",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-workflow", "tag-open-source", "tag-self-hostable"],
    shortDescription: "支持可视化搭建 AI 应用和工作流的开源平台。",
    recommendationReason: "原型资料将其作为长期使用的 LLMOps 平台收录，使用细节仍需编辑复核。",
    pricing: "freemium",
    platforms: ["web", "self-hosted"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-langgraph", "rec-n8n"],
    relatedProjectIds: ["project-automation-templates"],
    createdAt: "2026-01-09T00:00:00.000Z",
    updatedAt: "2026-07-04T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-n8n",
    slug: "n8n",
    name: "n8n",
    url: "https://n8n.io",
    categoryId: "category-agent-automation",
    tagIds: ["tag-workflow", "tag-workflow-building", "tag-open-source", "tag-self-hostable"],
    shortDescription: "节点式工作流自动化平台，支持自托管和系统集成。",
    recommendationReason: "原型资料将其作为日常使用的自动化平台收录，具体流程仍需编辑复核。",
    pricing: "freemium",
    platforms: ["web", "self-hosted"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "daily-use",
    featured: true,
    featuredOrder: 3,
    relatedScenarioIds: ["scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-dify", "rec-browser-use"],
    relatedProjectIds: ["project-automation-templates"],
    createdAt: "2026-01-10T00:00:00.000Z",
    updatedAt: "2026-07-03T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-browser-use",
    slug: "browser-use",
    name: "Browser Use",
    url: "https://browser-use.com",
    categoryId: "category-agent-automation",
    tagIds: ["tag-agent", "tag-browser-control", "tag-open-source", "tag-workflow-building"],
    shortDescription: "面向 Agent 的浏览器控制和网页任务自动化工具。",
    recommendationReason: "原型资料将其列为正在体验的浏览器自动化工具，评价仍需编辑复核。",
    pricing: "open-source",
    platforms: ["python"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "testing",
    featured: false,
    relatedScenarioIds: ["scenario-build-agent", "scenario-automation"],
    relatedRecommendationIds: ["rec-n8n"],
    relatedProjectIds: [],
    createdAt: "2026-01-11T00:00:00.000Z",
    updatedAt: "2026-07-02T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-obsidian",
    slug: "obsidian",
    name: "Obsidian",
    url: "https://obsidian.md",
    categoryId: "category-knowledge",
    tagIds: [
      "tag-notes",
      "tag-knowledge-base",
      "tag-personal-knowledge",
      "tag-local",
      "tag-desktop",
    ],
    shortDescription: "以本地 Markdown、双链和插件为核心的笔记工具。",
    recommendationReason: "原型资料将其作为日常使用的本地笔记工具收录，工作流仍需编辑复核。",
    pricing: "freemium",
    platforms: ["macos", "windows", "linux"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "daily-use",
    featured: true,
    featuredOrder: 4,
    relatedScenarioIds: ["scenario-knowledge-base", "scenario-automation"],
    relatedRecommendationIds: ["rec-notion"],
    relatedProjectIds: [],
    createdAt: "2026-01-12T00:00:00.000Z",
    updatedAt: "2026-07-01T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-notion",
    slug: "notion",
    name: "Notion",
    url: "https://notion.so",
    categoryId: "category-knowledge",
    tagIds: ["tag-notes", "tag-knowledge-base", "tag-personal-knowledge", "tag-web"],
    shortDescription: "结合文档、数据库和协作能力的知识管理工具。",
    recommendationReason: "原型资料将其作为长期使用的协作知识工具收录，判断仍需编辑复核。",
    pricing: "freemium",
    platforms: ["web", "macos", "ios", "android"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: [
      "scenario-knowledge-base",
      "scenario-automation",
      "scenario-indie-inspiration",
    ],
    relatedRecommendationIds: ["rec-obsidian"],
    relatedProjectIds: [],
    createdAt: "2026-01-13T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-zotero",
    slug: "zotero",
    name: "Zotero",
    url: "https://zotero.org",
    categoryId: "category-knowledge",
    tagIds: ["tag-citations", "tag-personal-knowledge", "tag-open-source", "tag-desktop"],
    shortDescription: "用于管理文献、引用和研究笔记的开源工具。",
    recommendationReason: "原型资料将其列为项目使用过的文献工具，具体经验仍需编辑复核。",
    pricing: "open-source",
    platforms: ["macos", "windows", "linux"],
    isOpenSource: true,
    selfHostable: false,
    relationship: "used-in-project",
    featured: false,
    relatedScenarioIds: ["scenario-knowledge-base"],
    relatedRecommendationIds: [],
    relatedProjectIds: [],
    createdAt: "2026-01-14T00:00:00.000Z",
    updatedAt: "2026-06-29T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-midjourney",
    slug: "midjourney",
    name: "Midjourney",
    url: "https://midjourney.com",
    categoryId: "category-content-creation",
    tagIds: ["tag-image-generation", "tag-content-creation", "tag-paid", "tag-web"],
    shortDescription: "通过文本提示生成视觉图像的商业服务。",
    recommendationReason: "原型资料将其作为长期使用的图像生成工具收录，宣传式表述已移除。",
    pricing: "paid",
    platforms: ["web"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "long-term-use",
    featured: false,
    relatedScenarioIds: ["scenario-media-production"],
    relatedRecommendationIds: [],
    relatedProjectIds: [],
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-06-28T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-figma",
    slug: "figma",
    name: "Figma",
    url: "https://figma.com",
    categoryId: "category-content-creation",
    tagIds: ["tag-ui-design", "tag-content-creation", "tag-web", "tag-desktop"],
    shortDescription: "支持多人协作的界面设计和原型工具。",
    recommendationReason: "原型资料将其作为日常使用的 UI 设计工具收录，工作方式仍需编辑复核。",
    pricing: "freemium",
    platforms: ["web", "macos", "windows"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "daily-use",
    featured: true,
    featuredOrder: 5,
    relatedScenarioIds: [
      "scenario-ai-website",
      "scenario-automation",
      "scenario-media-production",
      "scenario-indie-inspiration",
    ],
    relatedRecommendationIds: ["rec-excalidraw"],
    relatedProjectIds: [],
    createdAt: "2026-01-16T00:00:00.000Z",
    updatedAt: "2026-06-27T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-runway",
    slug: "runway",
    name: "Runway",
    url: "https://runwayml.com",
    categoryId: "category-content-creation",
    tagIds: ["tag-video-generation", "tag-content-creation", "tag-web"],
    shortDescription: "提供视频生成和编辑能力的在线创作工具。",
    recommendationReason: "原型资料将其列为持续关注的视频工具，能力和定价仍需编辑复核。",
    pricing: "freemium",
    platforms: ["web"],
    isOpenSource: false,
    selfHostable: false,
    relationship: "watching",
    featured: false,
    relatedScenarioIds: ["scenario-media-production", "scenario-indie-inspiration"],
    relatedRecommendationIds: ["rec-remotion"],
    relatedProjectIds: [],
    createdAt: "2026-01-17T00:00:00.000Z",
    updatedAt: "2026-06-26T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-rsshub",
    slug: "rsshub",
    name: "RSSHub",
    url: "https://rsshub.app",
    categoryId: "category-indie",
    tagIds: ["tag-rss", "tag-personal-knowledge", "tag-open-source", "tag-self-hostable"],
    shortDescription: "把多类网站内容转换为 RSS 订阅源的开源项目。",
    recommendationReason: "原型资料将其作为日常使用的 RSS 工具收录，具体订阅方式仍需编辑复核。",
    pricing: "open-source",
    platforms: ["web", "self-hosted"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "daily-use",
    featured: false,
    relatedScenarioIds: ["scenario-knowledge-base", "scenario-indie-inspiration"],
    relatedRecommendationIds: [],
    relatedProjectIds: [],
    createdAt: "2026-01-18T00:00:00.000Z",
    updatedAt: "2026-06-25T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-excalidraw",
    slug: "excalidraw",
    name: "Excalidraw",
    url: "https://excalidraw.com",
    categoryId: "category-indie",
    tagIds: ["tag-diagramming", "tag-indie-development", "tag-open-source", "tag-web"],
    shortDescription: "用于绘制手绘风格草图、流程和结构图的在线白板。",
    recommendationReason: "原型资料将其作为长期使用的白板工具收录，个人用法仍需编辑复核。",
    pricing: "open-source",
    platforms: ["web"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "long-term-use",
    featured: true,
    featuredOrder: 6,
    relatedScenarioIds: [
      "scenario-ai-website",
      "scenario-automation",
      "scenario-indie-inspiration",
    ],
    relatedRecommendationIds: ["rec-figma"],
    relatedProjectIds: [],
    createdAt: "2026-01-19T00:00:00.000Z",
    updatedAt: "2026-06-24T00:00:00.000Z",
  }),
  defineRecommendation({
    id: "rec-remotion",
    slug: "remotion",
    name: "Remotion",
    url: "https://remotion.dev",
    categoryId: "category-indie",
    tagIds: [
      "tag-programmatic-media",
      "tag-video-generation",
      "tag-indie-development",
      "tag-open-source",
    ],
    shortDescription: "使用 React 和代码生成视频内容的开源工具。",
    recommendationReason: "原型资料将其列为持续关注的程序化视频工具，使用判断仍需编辑复核。",
    pricing: "freemium",
    platforms: ["nodejs", "react"],
    isOpenSource: true,
    selfHostable: true,
    relationship: "watching",
    featured: false,
    relatedScenarioIds: ["scenario-media-production", "scenario-indie-inspiration"],
    relatedRecommendationIds: ["rec-runway"],
    relatedProjectIds: [],
    createdAt: "2026-01-20T00:00:00.000Z",
    updatedAt: "2026-06-23T00:00:00.000Z",
  }),
];
