import type { Scenario } from "../types";

const publishedAt = "2026-07-10T00:00:00.000Z";

export const scenarios: Scenario[] = [
  {
    id: "scenario-ai-website",
    slug: "ai-website",
    title: "用 AI 做一个网站",
    shortDescription: "从需求、界面、编码、数据到部署的工具组合。",
    longDescription: "按网站交付流程组织工具，步骤关系来自原型能力描述，具体个人选择理由仍需复核。",
    audience: ["希望用 AI 辅助完成网站交付的独立开发者。"],
    recommendationIds: [
      "rec-claude",
      "rec-chatgpt",
      "rec-figma",
      "rec-excalidraw",
      "rec-claude-code",
      "rec-cursor",
      "rec-supabase",
      "rec-vercel",
    ],
    steps: [
      {
        id: "website-requirements",
        order: 1,
        title: "整理需求",
        description: "澄清目标、范围和主要页面。",
        primaryRecommendationIds: ["rec-claude"],
        alternativeRecommendationIds: ["rec-chatgpt"],
        selectionReason: "两者都具备通用对话与文本整理能力。",
        notes: [],
      },
      {
        id: "website-design",
        order: 2,
        title: "设计界面",
        description: "整理信息结构并制作界面草图。",
        primaryRecommendationIds: ["rec-figma"],
        alternativeRecommendationIds: ["rec-excalidraw"],
        selectionReason: "Figma 负责正式界面，Excalidraw 适合快速草图。",
        notes: [],
      },
      {
        id: "website-code",
        order: 3,
        title: "实现代码",
        description: "在项目上下文中生成和修改代码。",
        primaryRecommendationIds: ["rec-claude-code"],
        alternativeRecommendationIds: ["rec-cursor"],
        selectionReason: "两者都面向代码库级修改。",
        notes: [],
      },
      {
        id: "website-data",
        order: 4,
        title: "准备数据服务",
        description: "为需要持久化的数据提供存储边界。",
        primaryRecommendationIds: ["rec-supabase"],
        alternativeRecommendationIds: [],
        selectionReason: "Supabase 提供以 Postgres 为核心的后端能力。",
        notes: [],
      },
      {
        id: "website-deploy",
        order: 5,
        title: "部署发布",
        description: "构建并发布 Web 应用。",
        primaryRecommendationIds: ["rec-vercel"],
        alternativeRecommendationIds: [],
        selectionReason: "Vercel 面向 Web 应用部署和持续交付。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
  {
    id: "scenario-build-agent",
    slug: "build-agent",
    title: "搭建一个 Agent",
    shortDescription: "从行为设计、流程编排到浏览器操作和外部自动化。",
    longDescription: "围绕 Agent 的决策、状态流转、工具使用和外部执行组织代表性工具。",
    audience: ["需要构建可调用工具和执行多步骤任务的开发者。"],
    recommendationIds: [
      "rec-claude",
      "rec-chatgpt",
      "rec-ollama",
      "rec-langgraph",
      "rec-dify",
      "rec-browser-use",
      "rec-n8n",
    ],
    steps: [
      {
        id: "agent-model",
        order: 1,
        title: "选择模型入口",
        description: "确定用于推理和文本处理的模型入口。",
        primaryRecommendationIds: ["rec-claude"],
        alternativeRecommendationIds: ["rec-chatgpt", "rec-ollama"],
        selectionReason: "覆盖云端助手和本地模型两类入口。",
        notes: [],
      },
      {
        id: "agent-orchestration",
        order: 2,
        title: "编排流程",
        description: "组织状态、分支、循环和工具调用。",
        primaryRecommendationIds: ["rec-langgraph"],
        alternativeRecommendationIds: ["rec-dify"],
        selectionReason: "分别代表代码式图编排和可视化平台。",
        notes: [],
      },
      {
        id: "agent-browser",
        order: 3,
        title: "连接浏览器",
        description: "让 Agent 执行网页任务。",
        primaryRecommendationIds: ["rec-browser-use"],
        alternativeRecommendationIds: [],
        selectionReason: "Browser Use 专注浏览器控制。",
        notes: [],
      },
      {
        id: "agent-automation",
        order: 4,
        title: "连接外部自动化",
        description: "把 Agent 结果连接到其他系统。",
        primaryRecommendationIds: ["rec-n8n"],
        alternativeRecommendationIds: ["rec-dify"],
        selectionReason: "n8n 提供通用节点式自动化。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
  {
    id: "scenario-knowledge-base",
    slug: "knowledge-base",
    title: "建立个人知识库",
    shortDescription: "从信息订阅、文献整理到长期笔记和辅助检索。",
    longDescription: "覆盖信息入口、结构化整理、引用管理和 AI 辅助理解的个人知识工作流。",
    audience: ["需要长期收集、整理和检索个人资料的人。"],
    recommendationIds: [
      "rec-rsshub",
      "rec-zotero",
      "rec-obsidian",
      "rec-notion",
      "rec-claude",
      "rec-chatgpt",
      "rec-ollama",
    ],
    steps: [
      {
        id: "knowledge-collect",
        order: 1,
        title: "收集信息",
        description: "将分散来源转换为稳定订阅。",
        primaryRecommendationIds: ["rec-rsshub"],
        alternativeRecommendationIds: [],
        selectionReason: "RSSHub 将多类网站内容转换为 RSS 订阅源。",
        notes: [],
      },
      {
        id: "knowledge-reference",
        order: 2,
        title: "管理文献",
        description: "保存来源、引用和研究资料。",
        primaryRecommendationIds: ["rec-zotero"],
        alternativeRecommendationIds: [],
        selectionReason: "Zotero 专注文献和引用管理。",
        notes: [],
      },
      {
        id: "knowledge-organize",
        order: 3,
        title: "整理笔记",
        description: "将信息沉淀为可持续维护的笔记。",
        primaryRecommendationIds: ["rec-obsidian"],
        alternativeRecommendationIds: ["rec-notion"],
        selectionReason: "分别代表本地 Markdown 和协作文档路径。",
        notes: [],
      },
      {
        id: "knowledge-understand",
        order: 4,
        title: "辅助理解",
        description: "使用模型总结和解释已有资料。",
        primaryRecommendationIds: ["rec-claude"],
        alternativeRecommendationIds: ["rec-chatgpt", "rec-ollama"],
        selectionReason: "覆盖云端对话与本地模型入口。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
  {
    id: "scenario-automation",
    slug: "automation",
    title: "自动化重复工作",
    shortDescription: "从流程草图到系统连接、网页操作和结果沉淀。",
    longDescription: "把重复任务拆为可观察步骤，再选择工作流、浏览器和知识工具执行。",
    audience: ["希望减少重复网页和系统操作的人。"],
    recommendationIds: [
      "rec-excalidraw",
      "rec-figma",
      "rec-n8n",
      "rec-dify",
      "rec-browser-use",
      "rec-notion",
      "rec-obsidian",
    ],
    steps: [
      {
        id: "automation-map",
        order: 1,
        title: "绘制流程",
        description: "明确输入、步骤、分支和输出。",
        primaryRecommendationIds: ["rec-excalidraw"],
        alternativeRecommendationIds: ["rec-figma"],
        selectionReason: "草图工具适合快速表达流程。",
        notes: [],
      },
      {
        id: "automation-build",
        order: 2,
        title: "搭建工作流",
        description: "连接数据和外部系统。",
        primaryRecommendationIds: ["rec-n8n"],
        alternativeRecommendationIds: ["rec-dify"],
        selectionReason: "分别覆盖通用自动化和 AI 工作流。",
        notes: [],
      },
      {
        id: "automation-browser",
        order: 3,
        title: "执行网页任务",
        description: "处理没有稳定接口的网页步骤。",
        primaryRecommendationIds: ["rec-browser-use"],
        alternativeRecommendationIds: [],
        selectionReason: "Browser Use 面向网页任务自动化。",
        notes: [],
      },
      {
        id: "automation-store",
        order: 4,
        title: "沉淀结果",
        description: "保存自动化结果供后续查阅。",
        primaryRecommendationIds: ["rec-notion"],
        alternativeRecommendationIds: ["rec-obsidian"],
        selectionReason: "覆盖协作和本地两种沉淀方式。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
  {
    id: "scenario-media-production",
    slug: "media-production",
    title: "生产图片和视频",
    shortDescription: "从内容规划、图像生成到版式和视频制作。",
    longDescription: "将文字规划、图像生成、视觉整理和视频输出拆成独立步骤。",
    audience: ["需要组合图像和视频工具完成内容生产的人。"],
    recommendationIds: [
      "rec-claude",
      "rec-chatgpt",
      "rec-midjourney",
      "rec-figma",
      "rec-excalidraw",
      "rec-runway",
      "rec-remotion",
    ],
    steps: [
      {
        id: "media-plan",
        order: 1,
        title: "规划内容",
        description: "整理主题、结构和素材需求。",
        primaryRecommendationIds: ["rec-claude"],
        alternativeRecommendationIds: ["rec-chatgpt"],
        selectionReason: "通用对话工具可用于内容结构整理。",
        notes: [],
      },
      {
        id: "media-image",
        order: 2,
        title: "生成图像",
        description: "根据内容方向制作视觉素材。",
        primaryRecommendationIds: ["rec-midjourney"],
        alternativeRecommendationIds: [],
        selectionReason: "Midjourney 提供图像生成能力。",
        notes: [],
      },
      {
        id: "media-layout",
        order: 3,
        title: "整理版式",
        description: "组合素材并设计页面或画面。",
        primaryRecommendationIds: ["rec-figma"],
        alternativeRecommendationIds: ["rec-excalidraw"],
        selectionReason: "覆盖正式设计和快速草图。",
        notes: [],
      },
      {
        id: "media-video",
        order: 4,
        title: "制作视频",
        description: "生成或编程制作视频内容。",
        primaryRecommendationIds: ["rec-runway"],
        alternativeRecommendationIds: ["rec-remotion"],
        selectionReason: "分别代表模型生成和程序化视频。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
  {
    id: "scenario-indie-inspiration",
    slug: "indie-inspiration",
    title: "寻找独立产品灵感",
    shortDescription: "从信号收集、概念草图到原型、演示和发布。",
    longDescription: "使用真实工具替换原型中的泛化占位条目，形成可执行的独立产品探索流程。",
    audience: ["需要持续发现、验证和表达独立产品想法的人。"],
    recommendationIds: [
      "rec-rsshub",
      "rec-notion",
      "rec-excalidraw",
      "rec-figma",
      "rec-cursor",
      "rec-claude-code",
      "rec-remotion",
      "rec-runway",
      "rec-vercel",
    ],
    steps: [
      {
        id: "indie-signal",
        order: 1,
        title: "收集信号",
        description: "订阅和整理持续出现的问题与产品信息。",
        primaryRecommendationIds: ["rec-rsshub"],
        alternativeRecommendationIds: ["rec-notion"],
        selectionReason: "覆盖订阅入口和资料整理。",
        notes: [],
      },
      {
        id: "indie-concept",
        order: 2,
        title: "绘制概念",
        description: "快速表达核心流程和界面。",
        primaryRecommendationIds: ["rec-excalidraw"],
        alternativeRecommendationIds: ["rec-figma"],
        selectionReason: "从草图逐步过渡到正式设计。",
        notes: [],
      },
      {
        id: "indie-prototype",
        order: 3,
        title: "实现原型",
        description: "在代码库中快速验证产品假设。",
        primaryRecommendationIds: ["rec-cursor"],
        alternativeRecommendationIds: ["rec-claude-code"],
        selectionReason: "两者都支持项目上下文中的代码修改。",
        notes: [],
      },
      {
        id: "indie-demo",
        order: 4,
        title: "制作演示",
        description: "生成便于介绍产品的演示内容。",
        primaryRecommendationIds: ["rec-remotion"],
        alternativeRecommendationIds: ["rec-runway"],
        selectionReason: "覆盖程序化和生成式视频路径。",
        notes: [],
      },
      {
        id: "indie-publish",
        order: 5,
        title: "发布验证",
        description: "部署原型并收集反馈。",
        primaryRecommendationIds: ["rec-vercel"],
        alternativeRecommendationIds: [],
        selectionReason: "Vercel 用于 Web 应用部署。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
];
