import type { Scenario } from "../types";

const publishedAt = "2026-07-16T00:00:00.000Z";

export const scenarios: Scenario[] = [
  {
    id: "scenario-ai-website",
    slug: "ai-website",
    title: "用 AI 做一个网站",
    shortDescription: "从需求、设计到代码和发布的一组实际工具入口。",
    longDescription: "按网站交付流程组织工具；步骤顺序与选择理由仍等待作者结合真实工作方式复核。",
    audience: ["希望借助 AI 完成网站设计、开发与发布的创作者和开发者。"],
    recommendationIds: [
      "rec-chatgpt",
      "rec-codex",
      "rec-claude-code",
      "rec-cursor",
      "rec-ccswitch",
      "rec-open-design",
      "rec-awesome-design-md",
      "rec-vercel",
      "rec-cloudflare",
    ],
    steps: [
      {
        id: "website-define",
        order: 1,
        title: "梳理需求",
        description: "明确目标用户、页面结构和验收边界。",
        primaryRecommendationIds: ["rec-chatgpt"],
        alternativeRecommendationIds: [],
        selectionReason: "用于把问题和需求整理成可讨论的初稿。",
        notes: [],
      },
      {
        id: "website-design",
        order: 2,
        title: "形成设计方向",
        description: "研究参考、确定视觉规则并制作界面方案。",
        primaryRecommendationIds: ["rec-open-design", "rec-awesome-design-md"],
        alternativeRecommendationIds: [],
        selectionReason: "分别用于形成设计方案与研究设计参考。",
        notes: [],
      },
      {
        id: "website-build",
        order: 3,
        title: "实现与检查",
        description: "在现有代码库中完成实现、审查和验证。",
        primaryRecommendationIds: ["rec-codex", "rec-claude-code"],
        alternativeRecommendationIds: ["rec-cursor", "rec-ccswitch"],
        selectionReason: "覆盖代码 Agent、编辑器协作与多工具配置管理。",
        notes: [],
      },
      {
        id: "website-publish",
        order: 4,
        title: "预览与发布",
        description: "通过预览链接检查内容后发布正式版本。",
        primaryRecommendationIds: ["rec-vercel"],
        alternativeRecommendationIds: ["rec-cloudflare"],
        selectionReason: "提供 Web 项目的预览与发布入口。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
  {
    id: "scenario-build-agent",
    slug: "build-agent",
    title: "搭建一个 Agent",
    shortDescription: "从定义任务到接入工具和工作流的探索路径。",
    longDescription: "将模型协作、编码 Agent、通用 Agent 和工作流工具拆分为可单独验证的步骤。",
    audience: ["希望构建可调用工具、可观察且有明确边界的 Agent 的开发者。"],
    recommendationIds: [
      "rec-chatgpt",
      "rec-codex",
      "rec-claude-code",
      "rec-ccswitch",
      "rec-hermes-agent",
      "rec-dify",
      "rec-n8n",
      "rec-agent-reach",
    ],
    steps: [
      {
        id: "agent-scope",
        order: 1,
        title: "定义任务与边界",
        description: "先说明输入、输出、权限和人工确认点。",
        primaryRecommendationIds: ["rec-chatgpt"],
        alternativeRecommendationIds: [],
        selectionReason: "用于讨论任务拆分与验收条件。",
        notes: [],
      },
      {
        id: "agent-build",
        order: 2,
        title: "实现能力",
        description: "在代码库中完成工具接入、检查和迭代。",
        primaryRecommendationIds: ["rec-codex", "rec-claude-code"],
        alternativeRecommendationIds: ["rec-ccswitch"],
        selectionReason: "覆盖编码 Agent 与多工具工作环境。",
        notes: [],
      },
      {
        id: "agent-run",
        order: 3,
        title: "组织运行流程",
        description: "验证 Agent、AI 应用和自动化工作流的职责边界。",
        primaryRecommendationIds: ["rec-hermes-agent", "rec-dify"],
        alternativeRecommendationIds: ["rec-n8n"],
        selectionReason: "覆盖通用 Agent、AI 应用与跨服务自动化。",
        notes: [],
      },
      {
        id: "agent-research",
        order: 4,
        title: "接入外部资料",
        description: "按信息来源和权限规则检索公开资料。",
        primaryRecommendationIds: ["rec-agent-reach"],
        alternativeRecommendationIds: [],
        selectionReason: "用于按来源选择合适的资料获取入口。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
  {
    id: "scenario-knowledge-base",
    slug: "knowledge-base",
    title: "建立个人知识库",
    shortDescription: "从信息发现到长期笔记整理的工具组合。",
    longDescription: "区分资料发现、主题整理、本地笔记和协作空间，避免把所有信息塞进同一个系统。",
    audience: ["需要持续收集、整理并重新使用资料的人。"],
    recommendationIds: ["rec-aihot", "rec-chatgpt", "rec-youmind", "rec-obsidian", "rec-notion"],
    steps: [
      {
        id: "knowledge-discover",
        order: 1,
        title: "发现资料",
        description: "收集值得继续阅读和追溯的来源线索。",
        primaryRecommendationIds: ["rec-aihot"],
        alternativeRecommendationIds: [],
        selectionReason: "作为 AI 相关动态和线索的聚合入口。",
        notes: [],
      },
      {
        id: "knowledge-understand",
        order: 2,
        title: "理解与提炼",
        description: "将资料整理成待验证的问题、摘要和结构。",
        primaryRecommendationIds: ["rec-chatgpt", "rec-youmind"],
        alternativeRecommendationIds: [],
        selectionReason: "分别覆盖对话式梳理和素材驱动的创作整理。",
        notes: [],
      },
      {
        id: "knowledge-store",
        order: 3,
        title: "沉淀与协作",
        description: "按本地长期积累或在线共享需求选择保存方式。",
        primaryRecommendationIds: ["rec-obsidian"],
        alternativeRecommendationIds: ["rec-notion"],
        selectionReason: "分别代表本地笔记和在线协作空间。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
  {
    id: "scenario-automation",
    slug: "automation",
    title: "自动化重复工作",
    shortDescription: "把重复、可定义且可验证的步骤组织成自动化流程。",
    longDescription: "先明确风险和人工确认点，再选择 Agent、流程工具和资料获取能力。",
    audience: ["希望减少跨服务重复操作，同时保留异常处理和人工确认的人。"],
    recommendationIds: [
      "rec-codex",
      "rec-ccswitch",
      "rec-aihot",
      "rec-hermes-agent",
      "rec-dify",
      "rec-n8n",
      "rec-agent-reach",
    ],
    steps: [
      {
        id: "automation-specify",
        order: 1,
        title: "定义可自动化步骤",
        description: "先写清输入、输出、失败处理和不能自动执行的操作。",
        primaryRecommendationIds: ["rec-codex"],
        alternativeRecommendationIds: ["rec-ccswitch"],
        selectionReason: "用于整理实现方案并管理多工具开发环境。",
        notes: [],
      },
      {
        id: "automation-orchestrate",
        order: 2,
        title: "搭建流程",
        description: "连接 AI 能力、服务接口和规则步骤。",
        primaryRecommendationIds: ["rec-n8n", "rec-dify"],
        alternativeRecommendationIds: ["rec-hermes-agent"],
        selectionReason: "覆盖工作流、AI 应用和 Agent 三种组织方式。",
        notes: [],
      },
      {
        id: "automation-sources",
        order: 3,
        title: "处理信息来源",
        description: "收集动态或按来源规则读取公开资料。",
        primaryRecommendationIds: ["rec-agent-reach"],
        alternativeRecommendationIds: ["rec-aihot"],
        selectionReason: "分别用于多来源读取与 AI 动态发现。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
  {
    id: "scenario-media-production",
    slug: "media-production",
    title: "生产图片、视频与演示",
    shortDescription: "从资料、视觉探索到视频和演示输出的创作路径。",
    longDescription: "将素材整理、图像和视频生成、程序化视频与演示文稿制作拆分为独立环节。",
    audience: ["需要将创意、图片、视频和演示内容组合成完整表达的人。"],
    recommendationIds: [
      "rec-youmind",
      "rec-open-design",
      "rec-kling",
      "rec-midjourney",
      "rec-remotion",
      "rec-ppt-master",
      "rec-guizang-ppt-skill",
      "rec-catchmeta",
    ],
    steps: [
      {
        id: "media-materials",
        order: 1,
        title: "整理素材与方向",
        description: "收集主题资料、视觉参考和提示词案例。",
        primaryRecommendationIds: ["rec-youmind", "rec-catchmeta"],
        alternativeRecommendationIds: [],
        selectionReason: "分别用于素材组织与提示词参考。",
        notes: [],
      },
      {
        id: "media-visuals",
        order: 2,
        title: "探索视觉与动态画面",
        description: "生成并筛选图片、视频概念和界面方向。",
        primaryRecommendationIds: ["rec-midjourney", "rec-kling"],
        alternativeRecommendationIds: ["rec-open-design"],
        selectionReason: "覆盖图像、视频和界面方案探索。",
        notes: [],
      },
      {
        id: "media-output",
        order: 3,
        title: "制作最终表达",
        description: "根据交付形式制作视频或演示文稿。",
        primaryRecommendationIds: ["rec-remotion", "rec-ppt-master"],
        alternativeRecommendationIds: ["rec-guizang-ppt-skill"],
        selectionReason: "覆盖程序化视频、可编辑 PPTX 与网页演示。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
  {
    id: "scenario-indie-inspiration",
    slug: "indie-inspiration",
    title: "寻找独立产品灵感",
    shortDescription: "从动态、参考、原型到发布的独立产品探索路径。",
    longDescription:
      "用公开资料和设计参考发现问题，再用小范围原型验证想法，而不是把灵感当成产品结论。",
    audience: ["希望发现、表达并验证独立产品想法的人。"],
    recommendationIds: [
      "rec-claude-code",
      "rec-cursor",
      "rec-vercel",
      "rec-notion",
      "rec-aihot",
      "rec-open-design",
      "rec-awesome-design-md",
      "rec-catchmeta",
      "rec-cloudflare",
    ],
    steps: [
      {
        id: "indie-signal",
        order: 1,
        title: "收集信号",
        description: "记录值得继续验证的问题、趋势和参考案例。",
        primaryRecommendationIds: ["rec-aihot", "rec-notion"],
        alternativeRecommendationIds: [],
        selectionReason: "分别用于发现线索和整理项目资料。",
        notes: [],
      },
      {
        id: "indie-concept",
        order: 2,
        title: "形成概念",
        description: "研究设计参考、提示词案例并形成可讨论的原型方向。",
        primaryRecommendationIds: ["rec-open-design", "rec-awesome-design-md"],
        alternativeRecommendationIds: ["rec-catchmeta"],
        selectionReason: "覆盖界面方案、设计研究和提示词资料。",
        notes: [],
      },
      {
        id: "indie-prototype",
        order: 3,
        title: "实现并发布验证",
        description: "通过最小可用原型收集真实反馈。",
        primaryRecommendationIds: ["rec-cursor", "rec-vercel"],
        alternativeRecommendationIds: ["rec-claude-code", "rec-cloudflare"],
        selectionReason: "覆盖编辑器协作、发布预览和终端式代码 Agent。",
        notes: [],
      },
    ],
    relatedArticles: [],
    publishStatus: "published",
    publishedAt,
    updatedAt: publishedAt,
  },
];
