import type { Tag } from "@/types";

export const tags: Tag[] = [
  { id: "tag-conversation", slug: "conversation", name: "对话", group: "capability", description: "通用对话与问答。", visible: true },
  { id: "tag-search", slug: "search", name: "搜索", group: "capability", description: "信息检索与来源发现。", visible: true },
  { id: "tag-code-generation", slug: "code-generation", name: "代码生成", group: "capability", description: "生成、修改或解释代码。", visible: true },
  { id: "tag-local-model", slug: "local-model", name: "本地模型", group: "capability", description: "在本地设备运行模型。", visible: true },
  { id: "tag-database", slug: "database", name: "数据库", group: "capability", description: "数据存储与查询。", visible: true },
  { id: "tag-deployment", slug: "deployment", name: "部署", group: "capability", description: "应用发布与持续交付。", visible: true },
  { id: "tag-agent", slug: "agent", name: "Agent", group: "capability", description: "Agent 设计与执行。", visible: true },
  { id: "tag-workflow", slug: "workflow", name: "工作流", group: "capability", description: "多步骤流程编排。", visible: true },
  { id: "tag-browser-control", slug: "browser-control", name: "浏览器控制", group: "capability", description: "自动操作网页和表单。", visible: true },
  { id: "tag-notes", slug: "notes", name: "笔记", group: "capability", description: "记录与组织信息。", visible: true },
  { id: "tag-knowledge-base", slug: "knowledge-base", name: "知识库", group: "capability", description: "结构化沉淀与检索知识。", visible: true },
  { id: "tag-citations", slug: "citations", name: "引用", group: "capability", description: "管理来源与文献引用。", visible: true },
  { id: "tag-image-generation", slug: "image-generation", name: "图像生成", group: "capability", description: "通过模型生成图像。", visible: true },
  { id: "tag-video-generation", slug: "video-generation", name: "视频生成", group: "capability", description: "生成或编辑视频内容。", visible: true },
  { id: "tag-ui-design", slug: "ui-design", name: "UI 设计", group: "capability", description: "界面设计和协作。", visible: true },
  { id: "tag-rss", slug: "rss", name: "RSS", group: "capability", description: "订阅和聚合信息源。", visible: true },
  { id: "tag-diagramming", slug: "diagramming", name: "草图与白板", group: "capability", description: "绘制草图、流程与结构。", visible: true },
  { id: "tag-programmatic-media", slug: "programmatic-media", name: "程序化媒体", group: "capability", description: "使用代码生成媒体内容。", visible: true },
  { id: "tag-agent-development", slug: "agent-development", name: "Agent 开发", group: "scenario", description: "搭建和调试 Agent。", visible: true },
  { id: "tag-indie-development", slug: "indie-development", name: "独立开发", group: "scenario", description: "独立产品设计与交付。", visible: true },
  { id: "tag-content-creation", slug: "content-creation", name: "内容创作", group: "scenario", description: "图文和视频生产。", visible: true },
  { id: "tag-personal-knowledge", slug: "personal-knowledge", name: "个人知识管理", group: "scenario", description: "个人信息收集与沉淀。", visible: true },
  { id: "tag-workflow-building", slug: "workflow-building", name: "工作流搭建", group: "scenario", description: "连接工具并自动执行流程。", visible: true },
  { id: "tag-open-source", slug: "open-source", name: "开源", group: "attribute", description: "提供开放源代码。", visible: true },
  { id: "tag-self-hostable", slug: "self-hostable", name: "可自托管", group: "attribute", description: "支持部署到自有环境。", visible: true },
  { id: "tag-paid", slug: "paid", name: "付费", group: "attribute", description: "主要能力需要付费。", visible: true },
  { id: "tag-api", slug: "api", name: "API", group: "attribute", description: "提供程序接口。", visible: true },
  { id: "tag-web", slug: "web", name: "Web", group: "attribute", description: "可通过网页使用。", visible: true },
  { id: "tag-desktop", slug: "desktop", name: "桌面端", group: "attribute", description: "提供桌面应用。", visible: true },
  { id: "tag-local", slug: "local", name: "本地运行", group: "attribute", description: "核心能力可在本地运行。", visible: true },
];
